/**
 * Pure Grounding Context Formatter & Assembler
 *
 * Formats contextual grounding blocks (VLM analysis, environmental awareness,
 * STMM/lifetime memories, semantic memories, recent topics, director visual scratchpad,
 * and salience telemetry) into system messages for LLM inference.
 *
 * This module is pure computation: zero Pinia, Vue, or browser dependencies.
 */

export interface GroundingMessage {
  role: 'system'
  content: string
}

export interface SemanticMemoryItem {
  kind?: string
  title?: string
  content: string
}

export interface RecentTopicItem {
  topic: string
  weight: number
}

export interface SalienceMetrics {
  lateLayerDeltas: number[]
  lateLayerMean: number
  hot: boolean
}

export type GroundingBlock
  = | { type: 'vlm', analysis: string }
    | { type: 'environmental', sensorPayload: string }
    | { type: 'shortTermMemory', context: string }
    | { type: 'lifetimeMemory', context: string }
    | { type: 'semanticMemories', memories: SemanticMemoryItem[] }
    | { type: 'recentTopics', topics: RecentTopicItem[] }
    | { type: 'directorScratchpad', scratchpad: string }
    | { type: 'salienceTelemetry', metrics: SalienceMetrics }

/**
 * 0. VLM Image Analysis (Forward Mode)
 * Injected unconditionally when a VLM forward hop produced a result.
 */
export function formatVlmBlock(analysis: string): GroundingMessage {
  return {
    role: 'system',
    content: `[IMAGE ANALYSIS]\nThe user attached an image. The following is an objective visual description generated by a vision model to inform your response. React naturally as the character — do not narrate or reference this block directly:\n---\n${analysis}`,
  }
}

/**
 * 1. System Sensors Telemetry
 * Injected when grounding / environmental sensors are active.
 */
export function formatEnvironmentalBlock(sensorPayload: string): GroundingMessage {
  return {
    role: 'system',
    content: `[ENVIRONMENTAL AWARENESS]\nThe following telemetry describes your current environmental context. Use it to stay grounded in the user's reality and inform your response. You may reference specific values (like time or active applications) if relevant to the conversation, but avoid a dry, technical recitation of the data.\n---\n${sensorPayload}`,
  }
}

/**
 * 1.5. Short-Term Memory (STMM Daily Continuity)
 */
export function formatShortTermMemoryBlock(context: string): GroundingMessage {
  return {
    role: 'system',
    content: context,
  }
}

/**
 * 1.6. Lifetime Memory Artifact
 */
export function formatLifetimeMemoryBlock(context: string): GroundingMessage {
  return {
    role: 'system',
    content: context,
  }
}

/**
 * 2. RAG Universe Memory Injection
 * Formats semantic long-term memory query matches.
 */
export function formatSemanticMemoriesBlock(memories: SemanticMemoryItem[]): GroundingMessage {
  const memoriesFormatted = memories
    .map(r => `[${(r.kind || 'Journal').toUpperCase()}] ${r.title || 'Memory'}\n${r.content}`)
    .join('\n\n')

  return {
    role: 'system',
    content: `[GROUNDED LONG-TERM MEMORIES]\nThe following long-term memory records from your history were retrieved based on the user's latest query. Use these memories to inform your response and maintain context continuity. Keep references to them natural and contextual:\n---\n${memoriesFormatted}`,
  }
}

/**
 * 3. Grounding Recent Topics Injection
 * Formats active conceptual threads and their weights.
 */
export function formatRecentTopicsBlock(topics: RecentTopicItem[]): GroundingMessage {
  const topicsFormatted = topics
    .map(t => `${t.topic} (weight: ${t.weight.toFixed(2)})`)
    .join(', ')

  return {
    role: 'system',
    content: `[RECENT TOPICS]\nYou have the following topics and conceptual threads active in your recent memory. Use them to maintain awareness of what has been discussed lately:\n---\n${topicsFormatted}`,
  }
}

/**
 * 4. Grounding Visual Scene State (Director's Scratchpad) Injection
 * Formats visual telemetry managed by the Director.
 */
export function formatDirectorScratchpadBlock(scratchpad: string): GroundingMessage {
  return {
    role: 'system',
    content: `[VISUAL STATE BOARD]\nThe following telemetry describes your current visual and spatial context, managed by the Director. Use this description to remain verbally aligned with your current surroundings, outfit, or held items. Keep references natural and contextual:\n---\n${scratchpad}`,
  }
}

/**
 * 5. Salience Gate Injection
 * Formats emotional/physical state deltas (L9-L11 cosine \u0394h).
 */
export function formatSalienceTelemetryBlock(metrics: SalienceMetrics): GroundingMessage {
  const layerReport = metrics.lateLayerDeltas.map((d, i) => `L${9 + i}=${d.toFixed(3)}`).join(' ')
  return {
    role: 'system',
    content: `[SALIENCE TELEMETRY]\nThis turn marks an emotional/physical beat. Recent-turn state deltas (late layers L9\u2013L11 cosine \u0394h) = ${layerReport}; mean \u0394cos = ${metrics.lateLayerMean.toFixed(3)}; verdict=${metrics.hot ? 'hot' : 'elevated'}. Keep a natural, in-character tone; do NOT narrate the numbers to the user.`,
  }
}

/**
 * Dispatches a single GroundingBlock to its corresponding formatter.
 */
export function formatGroundingBlock(block: GroundingBlock): GroundingMessage {
  switch (block.type) {
    case 'vlm':
      return formatVlmBlock(block.analysis)
    case 'environmental':
      return formatEnvironmentalBlock(block.sensorPayload)
    case 'shortTermMemory':
      return formatShortTermMemoryBlock(block.context)
    case 'lifetimeMemory':
      return formatLifetimeMemoryBlock(block.context)
    case 'semanticMemories':
      return formatSemanticMemoriesBlock(block.memories)
    case 'recentTopics':
      return formatRecentTopicsBlock(block.topics)
    case 'directorScratchpad':
      return formatDirectorScratchpadBlock(block.scratchpad)
    case 'salienceTelemetry':
      return formatSalienceTelemetryBlock(block.metrics)
  }
}

/**
 * Preserves block order, skips null/undefined blocks, and formats each active block.
 */
export function buildGroundingMessages(blocks: readonly (GroundingBlock | null | undefined)[]): GroundingMessage[] {
  const result: GroundingMessage[] = []
  for (const block of blocks) {
    if (block) {
      result.push(formatGroundingBlock(block))
    }
  }
  return result
}
