import type { GroundingBlock } from './grounding-assembler'

import { describe, expect, it } from 'vitest'

import {
  buildGroundingMessages,
  formatDirectorScratchpadBlock,
  formatEnvironmentalBlock,
  formatGroundingBlock,
  formatLifetimeMemoryBlock,
  formatRecentTopicsBlock,
  formatSalienceTelemetryBlock,
  formatSemanticMemoriesBlock,
  formatShortTermMemoryBlock,
  formatVlmBlock,

} from './grounding-assembler'

describe('grounding-assembler pure formatters', () => {
  it('formats VLM image analysis block with exact header and separator', () => {
    const analysis = 'The user is showing a blueprint of an architectural design.'
    const result = formatVlmBlock(analysis)

    expect(result.role).toBe('system')
    expect(result.content).toBe(
      `[IMAGE ANALYSIS]\nThe user attached an image. The following is an objective visual description generated by a vision model to inform your response. React naturally as the character — do not narrate or reference this block directly:\n---\n${analysis}`,
    )
  })

  it('formats environmental awareness block with sensor payload', () => {
    const payload = 'Time: 14:30 | OS: macOS | ActiveWindow: VSCode'
    const result = formatEnvironmentalBlock(payload)

    expect(result.role).toBe('system')
    expect(result.content).toBe(
      `[ENVIRONMENTAL AWARENESS]\nThe following telemetry describes your current environmental context. Use it to stay grounded in the user's reality and inform your response. You may reference specific values (like time or active applications) if relevant to the conversation, but avoid a dry, technical recitation of the data.\n---\n${payload}`,
    )
  })

  it('formats short-term memory block passing context through', () => {
    const stmm = '<stmm-summary>User discussed project milestones</stmm-summary>'
    const result = formatShortTermMemoryBlock(stmm)

    expect(result.role).toBe('system')
    expect(result.content).toBe(stmm)
  })

  it('formats lifetime memory block passing context through', () => {
    const ltmm = '<lifetime-record>Character loves tea and reading</lifetime-record>'
    const result = formatLifetimeMemoryBlock(ltmm)

    expect(result.role).toBe('system')
    expect(result.content).toBe(ltmm)
  })

  describe('formatSemanticMemoriesBlock', () => {
    it('formats multiple semantic memory items with uppercase kinds and custom titles', () => {
      const memories = [
        { kind: 'reflection', title: 'Stargazing Night', content: 'We looked at Andromeda together.' },
        { kind: 'journal', title: 'Afternoon Tea', content: 'Earl Grey with two sugars.' },
      ]
      const result = formatSemanticMemoriesBlock(memories)

      expect(result.role).toBe('system')
      expect(result.content).toContain('[GROUNDED LONG-TERM MEMORIES]')
      expect(result.content).toContain('[REFLECTION] Stargazing Night\nWe looked at Andromeda together.')
      expect(result.content).toContain('[JOURNAL] Afternoon Tea\nEarl Grey with two sugars.')
    })

    it('falls back to default kind JOURNAL and default title Memory when omitted', () => {
      const memories = [
        { content: 'A memorable quiet afternoon.' },
      ]
      const result = formatSemanticMemoriesBlock(memories)

      expect(result.content).toContain('[JOURNAL] Memory\nA memorable quiet afternoon.')
    })
  })

  describe('formatRecentTopicsBlock', () => {
    it('formats topics with weight rounded to two decimal places and joined by comma', () => {
      const topics = [
        { topic: 'Quantum Computing', weight: 0.854 },
        { topic: 'Coffee Brewing', weight: 0.6 },
        { topic: 'Retro Anime', weight: 0.999 },
      ]
      const result = formatRecentTopicsBlock(topics)

      expect(result.role).toBe('system')
      expect(result.content).toBe(
        `[RECENT TOPICS]\nYou have the following topics and conceptual threads active in your recent memory. Use them to maintain awareness of what has been discussed lately:\n---\nQuantum Computing (weight: 0.85), Coffee Brewing (weight: 0.60), Retro Anime (weight: 1.00)`,
      )
    })

    it('handles single topic gracefully', () => {
      const topics = [{ topic: 'Music', weight: 0.5 }]
      const result = formatRecentTopicsBlock(topics)
      expect(result.content).toContain('Music (weight: 0.50)')
    })
  })

  it('formats director scratchpad block with visual context', () => {
    const scratchpad = 'Location: Library balcony. Weather: Gentle rain. Outfit: Knitted cardigan.'
    const result = formatDirectorScratchpadBlock(scratchpad)

    expect(result.role).toBe('system')
    expect(result.content).toBe(
      `[VISUAL STATE BOARD]\nThe following telemetry describes your current visual and spatial context, managed by the Director. Use this description to remain verbally aligned with your current surroundings, outfit, or held items. Keep references natural and contextual:\n---\n${scratchpad}`,
    )
  })

  describe('formatSalienceTelemetryBlock', () => {
    it('formats salience telemetry with hot verdict when hot is true', () => {
      const metrics = {
        lateLayerDeltas: [0.123, 0.235, 0.346],
        lateLayerMean: 0.235,
        hot: true,
      }
      const result = formatSalienceTelemetryBlock(metrics)

      expect(result.role).toBe('system')
      expect(result.content).toContain('L9=0.123 L10=0.235 L11=0.346')
      expect(result.content).toContain('mean \u0394cos = 0.235')
      expect(result.content).toContain('verdict=hot')
    })

    it('formats salience telemetry with elevated verdict when hot is false', () => {
      const metrics = {
        lateLayerDeltas: [0.05, 0.06, 0.07],
        lateLayerMean: 0.06,
        hot: false,
      }
      const result = formatSalienceTelemetryBlock(metrics)

      expect(result.content).toContain('L9=0.050 L10=0.060 L11=0.070')
      expect(result.content).toContain('mean \u0394cos = 0.060')
      expect(result.content).toContain('verdict=elevated')
    })
  })

  describe('formatGroundingBlock discriminated dispatcher', () => {
    it('dispatches every supported block type to its proper formatter', () => {
      const blocks: GroundingBlock[] = [
        { type: 'vlm', analysis: 'Cat sitting by the window' },
        { type: 'environmental', sensorPayload: 'Battery: 95%' },
        { type: 'shortTermMemory', context: 'STMM' },
        { type: 'lifetimeMemory', context: 'LTMM' },
        { type: 'semanticMemories', memories: [{ content: 'Semantic' }] },
        { type: 'recentTopics', topics: [{ topic: 'T', weight: 0.9 }] },
        { type: 'directorScratchpad', scratchpad: 'Director' },
        { type: 'salienceTelemetry', metrics: { lateLayerDeltas: [0.1, 0.2, 0.3], lateLayerMean: 0.2, hot: true } },
      ]

      const formatted = blocks.map(formatGroundingBlock)
      expect(formatted).toHaveLength(8)
      expect(formatted[0].content).toContain('[IMAGE ANALYSIS]')
      expect(formatted[1].content).toContain('[ENVIRONMENTAL AWARENESS]')
      expect(formatted[2].content).toBe('STMM')
      expect(formatted[3].content).toBe('LTMM')
      expect(formatted[4].content).toContain('[GROUNDED LONG-TERM MEMORIES]')
      expect(formatted[5].content).toContain('[RECENT TOPICS]')
      expect(formatted[6].content).toContain('[VISUAL STATE BOARD]')
      expect(formatted[7].content).toContain('[SALIENCE TELEMETRY]')
    })
  })

  describe('buildGroundingMessages assembly order and null handling', () => {
    it('preserves exact 8-part grounding order and excludes null/undefined items', () => {
      const blocks: (GroundingBlock | null | undefined)[] = [
        { type: 'vlm', analysis: 'VLM analysis' },
        null,
        { type: 'environmental', sensorPayload: 'Sensors' },
        undefined,
        { type: 'shortTermMemory', context: 'STMM' },
        { type: 'lifetimeMemory', context: 'LTMM' },
        { type: 'semanticMemories', memories: [{ content: 'Semantic' }] },
        { type: 'recentTopics', topics: [{ topic: 'Topic', weight: 0.8 }] },
        { type: 'directorScratchpad', scratchpad: 'Director' },
        { type: 'salienceTelemetry', metrics: { lateLayerDeltas: [0.1, 0.2, 0.3], lateLayerMean: 0.2, hot: false } },
      ]

      const messages = buildGroundingMessages(blocks)
      expect(messages).toHaveLength(8)
      expect(messages.map(m => m.role)).toEqual(Array.from({ length: 8 }).fill('system'))

      expect(messages[0].content).toContain('[IMAGE ANALYSIS]')
      expect(messages[1].content).toContain('[ENVIRONMENTAL AWARENESS]')
      expect(messages[2].content).toBe('STMM')
      expect(messages[3].content).toBe('LTMM')
      expect(messages[4].content).toContain('[GROUNDED LONG-TERM MEMORIES]')
      expect(messages[5].content).toContain('[RECENT TOPICS]')
      expect(messages[6].content).toContain('[VISUAL STATE BOARD]')
      expect(messages[7].content).toContain('[SALIENCE TELEMETRY]')
    })

    it('returns empty array when given empty or all-null list', () => {
      expect(buildGroundingMessages([])).toEqual([])
      expect(buildGroundingMessages([null, undefined, null])).toEqual([])
    })
  })
})
