import { createTestingPinia } from '@pinia/testing'
import { setActivePinia } from 'pinia'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ref } from 'vue'

import { useChatOrchestratorStore } from '../chat'
import { useLLM } from '../llm'
import { useChatSessionStore } from './session-store'

vi.mock('vue-i18n', () => ({
  useI18n: () => ({
    t: (key: string) => key,
  }),
}))

vi.mock('../modules/airi-card', () => {
  const card = {
    name: 'Airi',
    extensions: { airi: {} },
  }
  return {
    useAiriCardStore: () => ({
      activeCard: ref(card),
      activeCardId: ref('card-airi'),
      systemPrompt: ref(''),
      isModelSyncPrevented: false,
      getCard: vi.fn(() => card),
      updateCard: vi.fn(),
    }),
  }
})

vi.mock('../providers', () => ({
  useProvidersStore: () => ({
    getProviderInstance: vi.fn(async () => ({})),
    getProviderConfig: vi.fn(() => ({})),
    getModelsForProvider: vi.fn(() => [{ id: 'test-model', capabilities: [] }]),
  }),
}))

vi.mock('../modules/consciousness', () => ({
  useConsciousnessStore: () => ({
    activeProvider: ref('test-provider'),
    activeModel: ref('test-model'),
  }),
}))

vi.mock('../modules/vision', () => ({
  useVisionStore: () => ({
    activeProvider: null,
    activeModel: null,
    promptShimDirect: '',
  }),
}))

vi.mock('../background', () => ({
  useBackgroundStore: () => ({
    currentBackground: ref(null),
    initializeStore: vi.fn(),
  }),
}))

describe('chat orchestrator queue & cancellation contracts (Q1-Q4, C5)', () => {
  let pinia: ReturnType<typeof createTestingPinia>

  beforeEach(() => {
    pinia = createTestingPinia({ createSpy: vi.fn, stubActions: false })
    setActivePinia(pinia)
  })

  // Q1: Ordinary main-window sends serialize. A new send does not automatically interrupt its predecessor.
  it('q1: serializes multiple sends and starts queued work only after predecessor finishes', async () => {
    const chatStore = useChatOrchestratorStore(pinia)
    const chatSession = useChatSessionStore(pinia)
    const llmStore = useLLM(pinia)

    const sessionId = 'session-q1'
    chatSession.activeSessionId = sessionId
    chatSession.setSessionMessages(sessionId, [])

    const dispatchOrder: string[] = []
    let resolveFirstStream: () => void
    let resolveSecondStream: () => void

    llmStore.stream = vi.fn(async (_model, _provider, msgs, options) => {
      const prompt = msgs[msgs.length - 1]?.content as string
      dispatchOrder.push(prompt)

      if (prompt.includes('First Message')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'First response generated by LLM stream.',
        })
        await new Promise<void>((resolve) => {
          resolveFirstStream = resolve
        })
      }
      else if (prompt.includes('Second Message')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'Second response generated by LLM stream.',
        })
        await new Promise<void>((resolve) => {
          resolveSecondStream = resolve
        })
      }
    })

    // Ingest First Message
    const firstPromise = chatStore.ingest('First Message', { triggerOnly: false }, sessionId)

    // Wait for First Message to enter stream
    await vi.waitFor(() => {
      expect(dispatchOrder).toContain('First Message')
      expect(chatStore.sending).toBe(true)
    })

    // Ingest Second Message while First is still in-flight
    const secondPromise = chatStore.ingest('Second Message', { triggerOnly: false }, sessionId)

    // Second message must NOT be dispatched to LLM yet (deferred first stream blocks later dispatch)
    expect(dispatchOrder).toEqual(['First Message'])

    // Complete First Message stream
    resolveFirstStream!()
    await firstPromise

    // Now Second Message should automatically dispatch
    await vi.waitFor(() => {
      expect(dispatchOrder).toEqual(['First Message', 'Second Message'])
    })

    // Complete Second Message stream
    resolveSecondStream!()
    await secondPromise

    // Both messages exist in session history in correct order
    const history = chatSession.getSessionMessages(sessionId)
    const assistantMessages = history.filter(m => m.role === 'assistant')
    expect(assistantMessages.length).toBe(2)
    expect(assistantMessages[0].content).toContain('First response')
    expect(assistantMessages[1].content).toContain('Second response')
  })

  // Q2: User Stop settles the active send without rejecting it as a failed draft submission.
  it('q2: settles active send cleanly on Stop without throwing or creating error bubble', async () => {
    const chatStore = useChatOrchestratorStore(pinia)
    const chatSession = useChatSessionStore(pinia)
    const llmStore = useLLM(pinia)

    const sessionId = 'session-q2'
    chatSession.activeSessionId = sessionId
    chatSession.setSessionMessages(sessionId, [])

    let streamAbortSignal: AbortSignal | undefined
    let resolveStream: () => void

    llmStore.stream = vi.fn(async (_model, _provider, _msgs, options) => {
      streamAbortSignal = options.abortSignal
      await options.onStreamEvent({
        type: 'text-delta',
        text: 'Partial thoughts that were interrupted by the user pressing stop.',
      })
      await new Promise<void>((resolve) => {
        resolveStream = resolve
        options.abortSignal?.addEventListener('abort', () => resolve(), { once: true })
      })
    })

    const ingestPromise = chatStore.ingest('Tell me something long', { triggerOnly: false }, sessionId)

    await vi.waitFor(() => {
      expect(chatStore.sending).toBe(true)
      expect(streamAbortSignal).toBeDefined()
    })

    // Stop current generation
    await chatStore.stopCurrentGeneration(sessionId)
    resolveStream!()

    // CRITICAL: ingestPromise MUST resolve, NOT reject!
    // Rejection would tell the composer that sending failed and restore the draft.
    await expect(ingestPromise).resolves.toBeUndefined()

    // Assert partial message persisted with aborted: true
    const history = chatSession.getSessionMessages(sessionId)
    const assistantMsg = history.find(m => m.role === 'assistant')
    expect(assistantMsg).toBeDefined()
    expect((assistantMsg as any)?.aborted).toBe(true)
    expect(assistantMsg?.content).toContain('Partial thoughts that were interrupted')

    // Must NOT contain error display bubble
    expect(assistantMsg?.content).not.toContain('⚠️ **Chat Generation Failed**')
  })

  // Q3 & Q4: Pending sends for stopped session reject; unrelated sessions remain queued.
  it('q3 & Q4: rejects pending sends for stopped session while leaving unrelated session queued', async () => {
    const chatStore = useChatOrchestratorStore(pinia)
    const chatSession = useChatSessionStore(pinia)
    const llmStore = useLLM(pinia)

    const sessionA = 'session-q3-a'
    const sessionB = 'session-q3-b'

    chatSession.activeSessionId = sessionA
    chatSession.setSessionMessages(sessionA, [])
    chatSession.setSessionMessages(sessionB, [])

    let resolveActiveStream: () => void
    let resolveSessionBStream: () => void
    const executedPrompts: string[] = []

    llmStore.stream = vi.fn(async (_model, _provider, msgs, options) => {
      const prompt = msgs[msgs.length - 1]?.content as string
      executedPrompts.push(prompt)

      if (prompt.includes('Active Send A1')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'Generating active message A1...',
        })
        await new Promise<void>((resolve) => {
          resolveActiveStream = resolve
          options.abortSignal?.addEventListener('abort', () => resolve(), { once: true })
        })
      }
      else if (prompt.includes('Send B1')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'Generating message for Session B...',
        })
        await new Promise<void>((resolve) => {
          resolveSessionBStream = resolve
        })
      }
    })

    // 1. Start in-flight send on Session A
    const sendA1Promise = chatStore.ingest('Active Send A1', { triggerOnly: false }, sessionA)

    await vi.waitFor(() => {
      expect(chatStore.sending).toBe(true)
      expect(executedPrompts).toContain('Active Send A1')
    })

    // 2. Queue a second send on Session A
    const sendA2Promise = chatStore.ingest('Pending Send A2', { triggerOnly: false }, sessionA)

    // 3. Queue a send on Session B
    const sendB1Promise = chatStore.ingest('Send B1', { triggerOnly: false }, sessionB)

    // Attach rejection listener to A2 to verify Q3/Q4
    let a2RejectedError: Error | undefined
    sendA2Promise.catch((err) => {
      a2RejectedError = err
    })

    // 4. Stop generation on Session A only
    await chatStore.stopCurrentGeneration(sessionA)
    resolveActiveStream!()

    // Active send A1 settles cleanly (Q2)
    await expect(sendA1Promise).resolves.toBeUndefined()

    // Pending send A2 MUST reject because session A was stopped (Q3)
    await vi.waitFor(() => {
      expect(a2RejectedError).toBeDefined()
      expect(a2RejectedError?.message).toContain('Chat session was reset before send could start')
    })

    // Pending send A2 was never dispatched to the LLM stream (Q4: logical cancellation)
    expect(executedPrompts).not.toContain('Pending Send A2')

    // 5. Unrelated Session B must NOT be rejected and should proceed to execute
    await vi.waitFor(() => {
      expect(executedPrompts).toContain('Send B1')
    })

    resolveSessionBStream!()
    await expect(sendB1Promise).resolves.toBeUndefined()

    const historyB = chatSession.getSessionMessages(sessionB)
    expect(historyB.some(m => m.role === 'assistant' && typeof m.content === 'string' && m.content.includes('Generating message for Session B'))).toBe(true)
  })

  // C5: A subsequent normal send works after cancellation.
  it('c5: allows subsequent normal send to execute cleanly after cancellation', async () => {
    const chatStore = useChatOrchestratorStore(pinia)
    const chatSession = useChatSessionStore(pinia)
    const llmStore = useLLM(pinia)

    const sessionId = 'session-c5'
    chatSession.activeSessionId = sessionId
    chatSession.setSessionMessages(sessionId, [])

    let stream1InFlight = false
    let resolveStream1: () => void
    let resolveStream2: () => void

    llmStore.stream = vi.fn(async (_model, _provider, msgs, options) => {
      const prompt = msgs[msgs.length - 1]?.content as string

      if (prompt.includes('First Prompt')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'Interrupted content that has streamed before stop.',
        })
        stream1InFlight = true
        await new Promise<void>((resolve) => {
          resolveStream1 = resolve
          options.abortSignal?.addEventListener('abort', () => resolve(), { once: true })
        })
      }
      else if (prompt.includes('Second Prompt')) {
        await options.onStreamEvent({
          type: 'text-delta',
          text: 'Completely successful second answer.',
        })
        await new Promise<void>((resolve) => {
          resolveStream2 = resolve
        })
      }
    })

    // Turn 1: Ingest and stop
    const turn1Promise = chatStore.ingest('First Prompt', { triggerOnly: false }, sessionId)
    await vi.waitFor(() => {
      expect(chatStore.sending).toBe(true)
      expect(stream1InFlight).toBe(true)
    })

    await chatStore.stopCurrentGeneration(sessionId)
    resolveStream1!()
    await turn1Promise

    expect(chatStore.sending).toBe(false)

    // Turn 2: Normal subsequent send
    const turn2Promise = chatStore.ingest('Second Prompt', { triggerOnly: false }, sessionId)
    await vi.waitFor(() => {
      expect(chatStore.sending).toBe(true)
    })

    resolveStream2!()
    await turn2Promise

    expect(chatStore.sending).toBe(false)

    const history = chatSession.getSessionMessages(sessionId)
    const assistantMessages = history.filter(m => m.role === 'assistant')
    expect(assistantMessages.length).toBe(2)
    expect((assistantMessages[0] as any).aborted).toBe(true)
    expect(assistantMessages[0].content).toContain('Interrupted content')
    expect((assistantMessages[1] as any).aborted).toBeUndefined()
    expect(assistantMessages[1].content).toContain('Completely successful second answer.')
  })
})
