#!/bin/bash
# AIRI Tamagotchi - Build script for Linux
# Usage: ./build.sh [--pkgbuild]
#   --pkgbuild   Generate PKGBUILD for Arch Linux (converts .deb)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[build]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
error() { echo -e "${RED}[error]${NC} $*" >&2; }

# Check prerequisites
command -v pnpm >/dev/null 2>&1 || { error "pnpm is required but not installed. Run: npm install -g pnpm"; exit 1; }
command -v node >/dev/null 2>&1 || { error "Node.js is required but not installed."; exit 1; }

# Parse args
PKGBUILD=false
for arg in "$@"; do
  case "$arg" in
    --pkgbuild) PKGBUILD=true ;;
    --help|-h)
      echo "Usage: ./build.sh [--pkgbuild]"
      echo ""
      echo "Options:"
      echo "  --pkgbuild   Generate PKGBUILD for Arch Linux"
      echo "  --help, -h   Show this help"
      exit 0
      ;;
    *) error "Unknown option: $arg"; exit 1 ;;
  esac
done

# Step 1: Typecheck
log "Step 1/3: Running typecheck..."
pnpm run typecheck

# Step 2: Build the Electron app
log "Step 2/3: Building Electron app..."
pnpm run build

# Step 3: Package for Linux
log "Step 3/3: Packaging for Linux (deb + rpm)..."
pnpm run build:linux

# Find the built artifacts
DIST_DIR="$SCRIPT_DIR/dist"
DEB_FILE=$(find "$DIST_DIR" -maxdepth 1 -name "*.deb" -type f | sort -V | tail -1)
RPM_FILE=$(find "$DIST_DIR" -maxdepth 1 -name "*.rpm" -type f | sort -V | tail -1)

log "Build complete!"
echo ""

if [ -n "$DEB_FILE" ]; then
  log "DEB package: $DEB_FILE"
  ls -lh "$DEB_FILE"
fi
if [ -n "$RPM_FILE" ]; then
  log "RPM package: $RPM_FILE"
  ls -lh "$RPM_FILE"
fi

# Generate PKGBUILD if requested
if [ "$PKGBUILD" = true ]; then
  if [ -z "$DEB_FILE" ]; then
    error "No .deb package found. Cannot generate PKGBUILD."
    exit 1
  fi

  log "Generating PKGBUILD..."

  # Extract version from package.json
  VERSION=$(python3 -c "
import json
with open('package.json') as f:
    d = json.load(f)
v = d.get('version', '0.0.0')
# Remove -stable suffix for Arch versioning
v = v.replace('-stable.', '.')
print(v)
")

  # Get .deb file info
  DEB_BASENAME=$(basename "$DEB_FILE")
  DEB_SIZE=$(stat -c%s "$DEB_FILE" 2>/dev/null || stat -f%z "$DEB_FILE" 2>/dev/null)

  # Generate MD5 of the .deb for integrity
  DEB_MD5=$(md5sum "$DEB_FILE" 2>/dev/null | cut -d' ' -f1 || md5 -q "$DEB_FILE" 2>/dev/null || echo "SKIP")

  PKGBUILD_DIR="$SCRIPT_DIR/pkgbuild"
  mkdir -p "$PKGBUILD_DIR"

  cat > "$PKGBUILD_DIR/PKGBUILD" << PKGBUILD_EOF
# Maintainer: AIRI Team <airi@moeru.ai>
# Generated by build.sh from ${DEB_BASENAME}

pkgname=airi
pkgver=${VERSION}
pkgrel=1
pkgdesc="AIRI — Self-hosted AI companion for Linux desktop (AiriOS)"
url="https://github.com/vi70x3/airi"
arch=('x86_64')
license=('MIT')
depends=('electron' 'libnotify' 'libxtst' 'nss' 'gtk3' 'alsa-lib')
optdeps=(
  'xdg-desktop-portal: screen capture support'
  'xdg-desktop-portal-wlr: Wayland screen capture'
  'xdg-desktop-portal-gnome: GNOME screen capture'
  'xdg-desktop-portal-kde: KDE screen capture'
)
conflicts=()
provides=('airi')
source=("file:///${DEB_BASENAME}")
md5sums=('${DEB_MD5}')

package() {
  # Extract the .deb archive
  cd "\$srcdir"
  ar x "${DEB_BASENAME}"
  tar xf data.tar.xz

  # Install application files
  cp -r usr/ "\$pkgdir/"

  # Install desktop entry
  install -Dm644 "\$pkgdir/usr/share/applications/ai.moeru.airi.desktop" \\
    "\$pkgdir/usr/share/applications/ai.moeru.airi.desktop"

  # Install icon
  install -Dm644 "\$pkgdir/usr/share/icons/hicolor/512x512/apps/ai.moeru.airi.png" \\
    "\$pkgdir/usr/share/icons/hicolor/512x512/apps/ai.moeru.airi.png"

  # Install binary symlink
  install -Dm755 "\$pkgdir/usr/bin/airi" "\$pkgdir/usr/bin/airi"

  # Cleanup extracted files
  rm -f "\$srcdir"/control.tar.* "\$srcdir"/data.tar.xz "\$srcdir"/debian-binary
}
PKGBUILD_EOF

  # Copy .deb into pkgbuild directory
  cp "$DEB_FILE" "$PKGBUILD_DIR/"

  # Copy desktop file and icon for reference
  cp "$SCRIPT_DIR/ai.moeru.airi.desktop" "$PKGBUILD_DIR/" 2>/dev/null || true
  cp "$SCRIPT_DIR/resources/icon.png" "$PKGBUILD_DIR/" 2>/dev/null || true

  log "PKGBUILD generated at: $PKGBUILD_DIR/PKGBUILD"
  log ""
  log "To build the Arch package:"
  log "  cd $PKGBUILD_DIR"
  log "  makepkg -si"
  echo ""
  log "Or install directly from .deb:"
  log "  sudo dpkg -i $DEB_FILE"
else
  echo ""
  log "To generate PKGBUILD for Arch:"
  log "  ./build.sh --pkgbuild"
  echo ""
  log "To install directly from .deb:"
  if [ -n "$DEB_FILE" ]; then
    log "  sudo dpkg -i $DEB_FILE"
  fi
  if [ -n "$RPM_FILE" ]; then
    log "  sudo dnf install $RPM_FILE"
  fi
fi
