import type { Tool } from '@xsai/shared-chat'

export const GEMINI_LIVE_MODEL = 'models/gemini-3.1-flash-live-preview'
export const GEMINI_LIVE_WS_BASE = 'wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContent'
export const MAX_TOOL_CALLS_PER_TURN = 5
export const GEMINI_LIVE_SAMPLE_RATE = 24000

export interface LatestTurnUsage {
  prompt: number
  completion: number
  total: number
  recordedAt: number
}

/**
 * Maps an AIRI tool (xsai Tool interface) to a Gemini functionDeclaration.
 * Purifies standard JSON Schema keywords ($schema, additionalProperties) and
 * resolves nullable types (anyOf / oneOf) for Gemini Bidi API compatibility.
 */
export function mapAiriToolToGemini(tool: Tool): Record<string, unknown> {
  const params = tool.function.parameters
    ? JSON.parse(JSON.stringify(tool.function.parameters))
    : { type: 'object', properties: {} }

  const cleanSchema = (obj: any) => {
    if (!obj || typeof obj !== 'object')
      return

    delete obj.$schema
    delete obj.additionalProperties

    if (obj.properties) {
      const requiredSet = new Set(Array.isArray(obj.required) ? obj.required : [])

      for (const [key, prop] of Object.entries(obj.properties)) {
        if (!prop || typeof prop !== 'object')
          continue

        const p = prop as any
        let isNullable = false

        // Handle anyOf (commonly generated by Zod for nullable/optional fields)
        if (p.anyOf && Array.isArray(p.anyOf)) {
          const nonNullSchemas = p.anyOf.filter((s: any) => s && s.type !== 'null')
          if (nonNullSchemas.length < p.anyOf.length) {
            isNullable = true
          }
          if (nonNullSchemas.length >= 1) {
            const desc = p.description
            Object.assign(p, nonNullSchemas[0])
            if (desc)
              p.description = desc
            delete p.anyOf
          }
        }

        // Handle oneOf
        if (p.oneOf && Array.isArray(p.oneOf)) {
          const nonNullSchemas = p.oneOf.filter((s: any) => s && s.type !== 'null')
          if (nonNullSchemas.length < p.oneOf.length) {
            isNullable = true
          }
          if (nonNullSchemas.length >= 1) {
            const desc = p.description
            Object.assign(p, nonNullSchemas[0])
            if (desc)
              p.description = desc
            delete p.oneOf
          }
        }

        // Handle type as array (e.g. ["string", "null"])
        if (Array.isArray(p.type)) {
          const nonNullTypes = p.type.filter((t: any) => t !== 'null')
          if (nonNullTypes.length < p.type.length) {
            isNullable = true
          }
          p.type = nonNullTypes[0] || 'string'
        }

        // Handle explicit null type
        if (p.type === 'null') {
          isNullable = true
          p.type = 'string'
        }

        if (isNullable) {
          requiredSet.delete(key)
        }

        cleanSchema(p)
      }

      if (requiredSet.size > 0) {
        obj.required = Array.from(requiredSet)
      }
      else {
        delete obj.required
      }
    }

    if (obj.items) {
      cleanSchema(obj.items)
    }
  }

  cleanSchema(params)

  if (params.type !== 'object') {
    params.type = 'object'
  }
  if (!params.properties) {
    params.properties = {}
  }

  return {
    name: tool.function.name,
    description: tool.function.description || '',
    parameters: params,
  }
}

/**
 * Coerces any provider-supplied token count to a safe non-negative integer.
 * Prevents string concatenation bugs ("2186" + "074" -> "2186074").
 */
export function sanitizeTokenCount(value: unknown): number {
  const num = Number(value)
  return (Number.isFinite(num) && num > 0) ? Math.floor(num) : 0
}

/**
 * Extracts normalized token counts from arbitrary provider usage payloads.
 */
export function extractInferenceUsage(usage: unknown): LatestTurnUsage | null {
  if (usage === null || usage === undefined) {
    return null
  }

  let total = 0
  let prompt = 0
  let completion = 0

  if (typeof usage === 'number') {
    total = sanitizeTokenCount(usage)
  }
  else if (typeof usage === 'object') {
    const u = usage as Record<string, unknown>
    prompt = sanitizeTokenCount(
      u.prompt_tokens
      ?? u.promptTokens
      ?? u.promptTokenCount
      ?? u.input_tokens
      ?? u.inputTokens,
    )
    completion = sanitizeTokenCount(
      u.completion_tokens
      ?? u.completionTokens
      ?? u.candidatesTokenCount
      ?? u.outputTokenCount
      ?? u.output_tokens
      ?? u.outputTokens,
    )
    total = sanitizeTokenCount(
      u.total_tokens
      ?? u.totalTokens
      ?? u.totalTokenCount,
    )

    if (total === 0 && (prompt > 0 || completion > 0)) {
      total = prompt + completion
    }
  }

  if (total > 0) {
    return {
      prompt,
      completion,
      total,
      recordedAt: Date.now(),
    }
  }

  return null
}

export interface LiveSetupOptions {
  model?: string
  voiceName?: string
  systemPrompt?: string
  resolvedTools?: Tool[]
  isGroundingEnabled?: boolean
}

/**
 * Builds the initial setup message frame for the Gemini Live WebSocket session.
 * CRITICAL: responseModalities MUST ALWAYS contain ['AUDIO'] to prevent Error 1007/1011.
 */
export function buildLiveSetupMessage(options: LiveSetupOptions = {}): Record<string, unknown> {
  const geminiTools: Record<string, unknown>[] = []

  if (options.resolvedTools && options.resolvedTools.length > 0) {
    geminiTools.push({
      functionDeclarations: options.resolvedTools.map(mapAiriToolToGemini),
    })
  }

  if (options.isGroundingEnabled) {
    geminiTools.push({ google_search: {} })
  }

  const generationConfig: Record<string, unknown> = {
    // NOTICE: responseModalities MUST ALWAYS contain 'AUDIO'.
    // The Bidi endpoint requires it for reasoning, tool-calling, and session stability.
    responseModalities: ['AUDIO'],
    speechConfig: {
      voiceConfig: {
        prebuiltVoiceConfig: {
          voiceName: options.voiceName || 'Puck',
        },
      },
    },
  }

  return {
    setup: {
      model: options.model || GEMINI_LIVE_MODEL,
      generationConfig,
      tools: geminiTools.length > 0 ? geminiTools : undefined,
      historyConfig: {
        initialHistoryInClientContent: true,
      },
      systemInstruction: {
        parts: [{
          text: options.systemPrompt || 'You are an AI assistant.',
        }],
      },
    },
  }
}

export interface ParsedBridgeMarker {
  toolName: string
  args: Record<string, any>
}

/**
 * Evaluates a special marker string to see if it qualifies as a bridged tool call.
 * Correctly parses JSON arguments directly without stringifying and regex-mangling them.
 */
export function parseBridgeMarker(marker: string): ParsedBridgeMarker | null {
  if (!marker || typeof marker !== 'string')
    return null

  const match = marker.match(/^<\|([\w-]+):([^|]*?)(?:\|>|<\/tool_call>|$)/)
    || marker.match(/^\[call_tool:([\w-]+),\s*([^\]]*?)(?:\]|<\/tool_call>|$)/)
    || marker.match(/<tool_call>([\w-]+)\((.*?)\)<\/tool_call>/s)
    || marker.match(/<tool_call>(\{.*?\})<\/tool_call>/s)

  if (!match)
    return null

  let toolName = ''
  let argsRaw = ''
  const potentialJson = match[1] || ''

  // Handle JSON format: <tool_call>{"name": "...", "arguments": ...}</tool_call>
  if (potentialJson.trim().startsWith('{')) {
    try {
      const parsed = JSON.parse(potentialJson)
      if (!parsed.name)
        return null

      toolName = parsed.name
      if (parsed.arguments && typeof parsed.arguments === 'object') {
        return { toolName, args: parsed.arguments }
      }
      argsRaw = typeof parsed.arguments === 'string' ? parsed.arguments : ''
    }
    catch {
      return null
    }
  }
  else {
    toolName = match[1]
    argsRaw = match[2] || ''
  }

  if (!toolName)
    return null

  const args: Record<string, any> = {}

  // Parse key-value arguments (e.g. key="val", count=5, active=true)
  const kvRegex = /(?:^|[, \n\t]+)\s*([\w-]+)\s*[:=]\s*(?:"([^"]*)"|'([^']*)'|(\d+(?:\.\d+)?)|(true|false)|(\{.*\}|\[.*\]))/g
  let kvMatch
  while ((kvMatch = kvRegex.exec(argsRaw)) !== null) {
    const [, key, valDouble, valSingle, valNum, valBool, valComplex] = kvMatch
    if (valDouble !== undefined) {
      args[key] = valDouble
    }
    else if (valSingle !== undefined) {
      args[key] = valSingle
    }
    else if (valNum !== undefined) {
      args[key] = Number.parseFloat(valNum)
    }
    else if (valBool !== undefined) {
      args[key] = valBool === 'true'
    }
    else if (valComplex !== undefined) {
      try {
        args[key] = JSON.parse(valComplex.replace(/'/g, '"'))
      }
      catch {
        args[key] = valComplex
      }
    }
  }

  // Fallback for single object-like string
  if (Object.keys(args).length === 0 && argsRaw.trim()) {
    try {
      const cleaned = argsRaw.trim().replace(/^\{/, '').replace(/\}$/, '').replace(/(\w+):/g, '"$1":').replace(/'/g, '"')
      Object.assign(args, JSON.parse(`{${cleaned}}`))
    }
    catch {}
  }

  // Fallback for single query parameter
  if (Object.keys(args).length === 0 && argsRaw.trim()) {
    args.query = argsRaw.trim()
  }

  return { toolName, args }
}

/**
 * Formats a tool execution response payload for the Gemini Bidi WebSocket stream.
 */
export function formatToolResponsePayload(
  callId: string | undefined,
  name: string,
  resultOrError: unknown,
): Record<string, unknown> {
  let response: unknown
  if (resultOrError instanceof Error) {
    response = { error: resultOrError.message }
  }
  else if (typeof resultOrError === 'string') {
    response = { output: resultOrError }
  }
  else if (resultOrError && typeof resultOrError === 'object') {
    response = resultOrError
  }
  else {
    response = { output: String(resultOrError ?? '') }
  }

  return {
    toolResponse: {
      functionResponses: [{
        id: callId,
        name,
        response,
      }],
    },
  }
}

export interface RateLimitCheckResult {
  allowed: boolean
  rateLimitPayload?: Record<string, unknown>
}

/**
 * Checks whether the current turn chain has exceeded the maximum allowed tool calls.
 */
export function checkToolRateLimit(
  currentCounter: number,
  maxLimit: number = MAX_TOOL_CALLS_PER_TURN,
  callInfo?: { callId?: string, name: string },
): RateLimitCheckResult {
  if (currentCounter >= maxLimit) {
    const errorMsg = `Tool call limit reached (${maxLimit} per turn). Please respond to the user.`
    return {
      allowed: false,
      rateLimitPayload: callInfo
        ? formatToolResponsePayload(callInfo.callId, callInfo.name, new Error(errorMsg))
        : undefined,
    }
  }
  return { allowed: true }
}

/**
 * Decodes base64-encoded PCM16 little-endian audio bytes into normalized Float32 samples (-1.0 to 1.0).
 */
export function decodePcm16Chunk(base64Data: string): Float32Array {
  if (!base64Data) {
    return new Float32Array(0)
  }

  const binaryString = typeof atob === 'function'
    ? atob(base64Data)
    : Buffer.from(base64Data, 'base64').toString('binary')

  const bytes = new Uint8Array(binaryString.length)
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i)
  }

  const pcm16 = new Int16Array(bytes.buffer)
  const float32 = new Float32Array(pcm16.length)
  for (let i = 0; i < pcm16.length; i++) {
    float32[i] = pcm16[i] / 32768
  }

  return float32
}
